package org.photonvision.vision.opencv.aruco;



import org.opencv.core.Mat;
import org.opencv.core.MatOfDouble;
import org.photonvision.vision.calibration.CameraCalibrationCoefficients;

/**
 * Camera parameters needed to 3d rendering. They will be loaded from a file
 * in xml format generated by the OpenCV's calibration algorithm.
 * The parameters used are the camera matrix and the distorsion coefficient matrix.
 * @author Rafael Ortega
 *
 */
public class CameraParameters {

    private final CameraCalibrationCoefficients cameraCalibrationCoefficients;
    
    public CameraParameters(CameraCalibrationCoefficients cameraCalibrationCoefficients){
        this.cameraCalibrationCoefficients = cameraCalibrationCoefficients;
    }
    
    /**Indicates whether this object is valid
     */
    public boolean isValid(){
        return true;
    }
    
    public Mat getCameraMatrix(){
        return cameraCalibrationCoefficients.getCameraIntrinsicsMat();
    }
    
    public MatOfDouble getDistCoeff(){
        return cameraCalibrationCoefficients.getCameraExtrinsicsMat();
    }

}
